[package]
name = "windows-play"
version = "0.1.0"
edition = "2024"
default-run = "main"

[dependencies]
anyhow = "1.0.100"
env_logger = "0.11.8"
log = "0.4.28"
tokio = { version = "1.48.0", features = ["macros", "rt", "rt-multi-thread"] }
windows = { version = "0.62.2", features = ["Devices_Enumeration", "Media_Audio", "System", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader", "Win32_UI_Controls", "Win32_UI_HiDpi", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
